version: "3.9"

services:
  app:
    build: .
    container_name: expanders_app
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: >
      sh -c "
        npm run db:migrate &&
        npm run db:seed &&
        npm start
      "
